### ISSUE TITLE
Integration with velocity.js

### ISSUE THREAD

**Issue by dcworldwide** [gwendall/meteor-template-animations#2]
Hi, package looks good. Is it possible to integrate with velocity js?

It seems like the package is intended to be decoupled from the animation engine? If so i agree thats a good design. But i'm unsure how to integrate it with velocity.

**Comment by gwendall** [comment]
What this package does is set classes on added / removed elements. To integrate with velocity, you may just use plain uihooks - made easy with [this package](http://github.com/gwendall/meteor-ui-hooks). You may just do something like:

``` javascript
Template.layout.uihooks({
  ".item": {
    container: ".container",
    insert: function(node, next, tpl) {
      $(node).insertBefore(next).velocity({ translateX: [0, -100%] }, {
        duration: 500,
        easing: "ease-in-out",
        queue: false
      });
    },
    remove: function(node, tpl) {
      $(node).velocity({ translateX: 100% }, {
        duration: 500,
        easing: "ease-in-out",
        queue: false,
        complete: function() {
          $(node).remove();
        }
      });
    }
  }
});
```

**Comment by dcworldwide** [comment]
Really neat solution..Thanks for your reply
